### ISSUE TITLE
[Bug]: All apps crashes after opening

### ISSUE THREAD

**Issue by TakeruF** [PlayCover/PlayCover#1262]
### Describe the bug

# 2023.12.12

THERE WAS NO OPTION FOR SONOMA, SO I CHOOSE VENTURA BELOW. I'M USING SONOMA 14.2
FULL CRASH REPORT↓↓
https://drive.google.com/file/d/1b_Gphum8psZEHxdljDuOM1jaRGLYD1ic/view?usp=drive_link

install from [PlayCover_3.0.0_beta.dmg](https://github.com/PlayCover/PlayCover/releases/download/3.0.0-beta.1/PlayCover_3.0.0_beta.dmg)

I have reset and rebooted. also followed [https://github.com/PlayCover/PlayCover/issues/311](https://github.com/PlayCover/PlayCover/issues/311) and [https://github.com/PlayCover/PlayCover/issues/257](https://github.com/PlayCover/PlayCover/issues/257)

install ipa from [https://decrypt.day/app/id1559483982#download-box](https://decrypt.day/app/id1559483982#download-box) (the right one which is free)

It was also unable to launch Genshin Impact (from decrypt.day)
<img width="372" alt="SCR-20231212-shpo" src="https://github.com/PlayCover/PlayCover/assets/99144975/71fcb009-4762-4c0d-b163-b3420abebe86">

### Steps to reproduce

# 2023.12.12

 THERE WAS NO OPTION FOR SONOMA, SO I CHOOSE VENTURA BELOW. I'M USING SONOMA 14.2

install from [PlayCover_3.0.0_beta.dmg](https://github.com/PlayCover/PlayCover/releases/download/3.0.0-beta.1/PlayCover_3.0.0_beta.dmg)

I have reset and rebooted. also followed [https://github.com/PlayCover/PlayCover/issues/311](https://github.com/PlayCover/PlayCover/issues/311) and [https://github.com/PlayCover/PlayCover/issues/257](https://github.com/PlayCover/PlayCover/issues/257)

install ipa from [https://decrypt.day/app/id1559483982#download-box](https://decrypt.day/app/id1559483982#download-box) (the right one which is free)

It was also unable to launch Genshin Impact (from decrypt.day)
<img width="372" alt="SCR-20231212-shpo" src="https://github.com/PlayCover/PlayCover/assets/99144975/71fcb009-4762-4c0d-b163-b3420abebe86">

### Expected behaviour

All apps crashes after opening

### Crash log

```shell
It was too long, so I stored on my google drive as a plain text file↓↓
https://drive.google.com/file/d/1b_Gphum8psZEHxdljDuOM1jaRGLYD1ic/view?usp=drive_link
```

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [X] Yes my issue is written in English

**Comment by ShiGuangAlex** [comment]
I ran into the same problem, all the games didn't work, I tried to uninstall the game and playcover, and downloaded the latest night version of playcover (version 572), and re-installing the game still didn't work.

**Comment by ShiGuangAlex** [comment]
I updated xcode to the latest version this morning and it's working, it seems to have something to do with xcode dependencies.

**Comment by mattam301** [comment]
> I updated xcode to the latest version this morning and it's working, it seems to have something to do with xcode dependencies.

Excuse me, could you help me update xcode?

**Comment by TakeruF** [comment]
> > I updated xcode to the latest version this morning and it's working, it seems to have something to do with xcode dependencies.
> 
> Excuse me, could you help me update xcode?

me, too.
I have reinstalled Xcode 15.1, but the issue hasn't been solved yet.
I don't know if these are related, but the appearance of a popup (attached) while installing ipa.
<img width="1012" alt="SCR-20231215-pybz" src="https://github.com/PlayCover/PlayCover/assets/99144975/995cc189-64db-4654-843e-111bfdb5ecf9">

**Comment by ShiGuangAlex** [comment]
> > I updated xcode to the latest version this morning and it's working, it seems to have something to do with xcode dependencies.
> 
> Excuse me, could you help me update xcode?

I'm not sure if your problem is the same as mine, I'm using macOS 14.2, playcover is using the nightly version (version 573), and I updated xcode to 15.1,it works fine.

**Comment by ShiGuangAlex** [comment]
I also noticed that while playcover didn't actively request disk access, we had to give it permission manually, otherwise we would have some weird issues (like not being able to uninstall installed games). This is just a tip, I'm not sure if it has anything to do with the game crashing.

**Comment by TakeruF** [comment]
**Thanks!**
**The problem was solved!!** I followed as [zhengyongtao](https://github.com/zhengyongtao) told me.
Here are my steps.
1. install the newest [nightly version of Playcover](https://nightly.link/playcover/playcover/workflows/2.nightly_release/develop).
2. Give a grant access to the Full Disk in mac's System Setting.

**All the apps are working fine. Thank you.**
I will leave this issue open for about a month in case somebody else or I encounter the same problem.

**Comment by Dudy66** [comment]
same for me, since the update, impossible to launch a game

**Comment by MEMORIEmusic** [comment]
Duplicate of #1108

**Comment by TheMoonThatRises** [comment]
It isn't necessary to keep this issue open as it is a duplicate of #1108 and that issue is pinned.

**Comment by Gravarty** [comment]
Still not working with the latest nightly build. I can launch the app for only one time and after that it keeps crashing.

Time Awake Since Boot: 3000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000001, 0x00000001942790f8

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [7839]

**Comment by phuwn** [comment]
> **Thanks!** **The problem was solved!!** I followed as [zhengyongtao](https://github.com/zhengyongtao) told me. Here are my steps.
> 
> 1. install the newest [nightly version of Playcover](https://nightly.link/playcover/playcover/workflows/2.nightly_release/develop).
> 2. Give a grant access to the Full Disk in mac's System Setting.
> 
> **All the apps are working fine. Thank you.** I will leave this issue open for about a month in case somebody else or I encounter the same problem.

work like a charm
