### ISSUE TITLE
[Bug]: App preferences for Genshin Impact fails to be saved properly

### ISSUE THREAD

**Issue by Wind-Explorer** [PlayCover/PlayCover#254]
### Describe the bug

When attempting to alter app preferences for Genshin Impact, after pressing "OK" to close out of the settings pane, the settings are not saved. (Side note: This only happens with Genshin Impact)

Below is a video illustration of the issue:

https://user-images.githubusercontent.com/66894537/187015012-21e4189c-b2c5-4071-ab11-f0c27bbe5433.mp4

### Steps to reproduce

With Genshin Impact installed, change any settings in the App Preferences pane

### Expected behaviour

When pressing OK, settings are saved

### What version of PlayCover are you using?

Nightly/beta

### What version of macOS are you using?

Monterey (macOS 12)

### Issue Language

- [x] Yes my issue is written in English

**Comment by ZhichGaming** [comment]
Does this only happen with Genshin Impact?

**Comment by JoseMoreville** [comment]
Are you using the latest build?

**Comment by Depal1** [comment]
I think this was fixed on nightlies, was it not?

**Comment by Wind-Explorer** [comment]
> Does this only happen with Genshin Impact?

@ZhichGaming It seems like it..settings for other apps works correctly.

**Comment by Wind-Explorer** [comment]
> Are you using the latest build?

@JoseMoreville Yes latest nightly build.

**Comment by Wind-Explorer** [comment]
> I think this was fixed on nightlies, was it not?

@Depal1 Unfortunately not, issue persists in the latest nightly build.

**Comment by ZhichGaming** [comment]
Have you tried a clean reinstall? Try clearing Genshin impact's app preferences.

**Comment by zanderp25** [comment]
@Wind-Explorer Is this still an issue with the latest nightly?

**Comment by IsaacMarovitz** [comment]
App settings have significantly changed since this issue was opened, this issue has been resolved.
